# Generated by Django 3.2 on 2021-04-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fcc_profile_url',
            new_name='college_profile_url',
        ),
    ]
